version: "3.9"
services:
  postgres:
    container_name: diploma_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRESQL_USER -d $POSTGRESQL_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: "no"

